### ISSUE TITLE
Blockbench Plugin - No Tools -> BAMO Export Option

### ISSUE THREAD

**Issue by daftinquisitor** [tmudway/BAMO#15]
Not sure if this is a compatibility issue due to updates to Blockbench, but the plugin doesn't seem to work properly any longer. When I install the plugin initially, it throws a popup error:

Failed to load plugin
Ensure that the base file name of the plugin matches the plugin ID bamo, as specified in Plugin.register().

After clicking OK, it still shows in the Installed Plugins list, albeit with an error marker. It will let me start a New -> BAMO Model file, and will save fine, but the Export options (and possibly some other settings) appear to be missing.

**Comment by tmudway** [comment]
Are you saving the file as exactly "bamo.js", same capitalization? I changed it from uppercase to lowercase for the latest update to match existing plugin formatting

**Comment by daftinquisitor** [comment]
Ah, looks like that was actually the issue. I saved the file as-is from the Releases, and there it was "BAMO.js". Renaming to all lowercase made it work as intended.

**Comment by tmudway** [comment]
was this the 1.19 version? Looks like I didnt configure the name change correctly when I exported that one

**Comment by daftinquisitor** [comment]
EDIT: Actually I think that was the one, I just grabbed from the newest release and wasn't paying that much attention to version when I did.
